### ISSUE TITLE
Question: Why don't we have a Gitter?

### ISSUE THREAD

**Issue by akilegaspi** [bitemyapp/esqueleto#132]
Given the circumstances that this channel may not always be active and that the documentation may need to be updated.

I think that a Gitter channel for `esqueleto` would be very beneficial for new people using the library and that it would "possibly" be a faster channel to answer questions than having to post an issue here.

**Comment by bitemyapp** [comment]
Because I didn't have a reasonable expectation that I or others would have time to deal with synchronous communication. For my part, I got married yesterday and I will be hiding in the mountains for 2-3 weeks.

I really strongly prefer asynchronous communication (GitHub comments, email threads) for OSS work regardless.

**Comment by parsonsmatt** [comment]
People are always welcome to post a question *of any kind* on this GitHub repo - I will be happy to help out.

If you want more of a chatroom, I'm also frequently on the `#haskell` and `#haskell-beginners` channels on the FPChat slack ([invite link here](https://fpchat-invite.herokuapp.com/)). Many folks there use the library and can help and you can ping me directly as well.

**Comment by parsonsmatt** [comment]
I'm going to close this out. If someone wants to maintain a gitter channel and is maintainer-level familiar with the library, I'd be happy to have one, but it would appear that the current maintainers don't have bandwidth to watch that channel.
