### ISSUE TITLE
A newbie Esqueleto question

### ISSUE THREAD

**Issue by gbordyugov** [bitemyapp/esqueleto#16]
Dear Chris,

I'm a Haskell newbie, trying to understand the library. The thing
that currently puzzles the most is the following: How does this code:

```
do people <- select $
             from $ \person -> do
             return person
   liftIO $ mapM_ (putStrLn . personName . entityVal) people
```

know what table we're querying? Is it derived from the application of
`personName`? What would happen if we drop the last line, making a
full stop after `return person`? And how does this mechanism work with
joins where you've got something like

`from $ \(a, b) -> ...`

?

I'm also wondering whether there is a minimal working code using
Esqueleto, I'm struggling to get even the simplest query working.

Hope it was not too many questions at once and many thanks!

Grisha

**Comment by bitemyapp** [comment]
>How does this code: ... know what table we're querying?

>Is it derived from the application of `personName`?

Yes.

>What would happen if we drop the last line, making a full stop after return person?

Assuming no other context cues for it to know the type, you'd get an ambiguous type error probably. You could make the code work if you made the generic query explicitly polymorphic. Then it'd essentially be a dummy query waiting for the type to tell it what table to pull it from.

I was able to infer the type in GHCi:

```
select $ from $ \t -> return t
  :: (MonadIO m, PersistUniqueRead backend, IsPersistBackend backend,
      PersistQueryRead backend, EI.SqlSelect a r,
      Database.Esqueleto.Internal.Language.From
        SqlQuery SqlExpr SqlBackend a,
      BaseBackend backend ~ SqlBackend) =>
     ReaderT backend m [r]
```

From there I can assert a type for `r` to essentially generate a query for any type `r` which has the necessary instances.


>And how does this mechanism work with joins where you've got something like
>from $ \(a, b) -> ...

```
Prelude> :t select $ from $ \(s `InnerJoin` t) -> return (s, t)
select $ from $ \(s `InnerJoin` t) -> return (s, t)
  :: (MonadIO m, PersistUniqueRead backend, IsPersistBackend backend,
      PersistQueryRead backend, EI.SqlSelect t ra, EI.SqlSelect t1 rb,
      Database.Esqueleto.Internal.Language.FromPreprocess
        SqlQuery SqlExpr SqlBackend t,
      Database.Esqueleto.Internal.Language.FromPreprocess
        SqlQuery SqlExpr SqlBackend t1,
      BaseBackend backend ~ SqlBackend) =>
     ReaderT backend m [(ra, rb)]
```

More constraints. Not sure that'll work without an `on` clause specifying the `JOIN` fields. I think you'd need more machinery like https://github.com/pseudonom/dovetail to get automatic JOIN. I could be wrong.

>I'm also wondering whether there is a minimal working code using Esqueleto, I'm struggling to get even the simplest query working.

Yes, Esqueleto was very difficult for me starting out too. I'm going to be conservative with the library for now but this is something I'd like to amend. In lieu of changing the library, I am trying to get more public examples of Esqueleto queries out there because I've seen working examples make learning Esqueleto a lot easier for my coworkers.

Here's one: https://github.com/alexeyzab/cards-with-comrades/blob/master/Model.hs#L34-L40

I realize it's a touch trivial and may not help you, but it's at least an end-to-end application.

Follow the repository and hopefully there'll be more examples soon.

Closing this issue as solved for now.

**Comment by gbordyugov** [comment]
Thanks a lot for the detailed reply!
