### ISSUE TITLE
Question on 'just' implementation

### ISSUE THREAD

**Issue by googleson78** [bitemyapp/esqueleto#184]
Looking at the [implementation for `just`](https://hackage.haskell.org/package/esqueleto-3.3.3.0/docs/src/Database.Esqueleto.Internal.Internal.html#just):
```haskell
just :: SqlExpr (Value typ) -> SqlExpr (Value (Maybe typ))
just (ERaw p f)             = ERaw p f
just (ECompositeKey f)      = ECompositeKey f
just (EAliasedValue i v)    = EAliasedValue i (just v)
just (EValueReference i i') = EValueReference i i'
```

all it seems to be doing is traversing a structure. Is the point of this definition to blow up on anything that isn't one of the matched constructors and/or make the spine of the `SqlExpr` strict? I am probably entirely missing something (?).

Context:
I'm asking because I'm interested in implementing a custom `Maybe`-like type, but where the `Nothing` value isn't `NULL` (so I can use it in an unique constraint), but rather some special value that I've selected to mean "missing".

**Comment by parsonsmatt** [comment]
The structure traversal is changing the type of the value subtly. A `SqlExpr (Value Int)` does not *contain* an `Int` anywhere - but it may contain a field projection from a table (`foo.age`), or a raw value (represented as a tuple of the `Text.Builder` of the query and a `[PersistValue]` of potential substitutions).

The type is *sort of* a phantom. I say "sort of" because it's a GADT and you can know which constructors were used if it starts with `Value` or `ValueList` or `Entity` etc. We could *also* write this using `unsafeCoerce` and it would actually be safe, because the underlying value does not change at all, only the type inside the `Value`.

For a simpler example, consider a "cast" function on the `Const` data type.

```haskell
newtype Const value nope = Const value
```

We've got a value `a :: Const String Int` and we want to cast the type to `Const String Double`. Let's write the function:

```haskell
castConst :: Const String Int -> Const String Double
castConst (Const str) = Const str
```

You might see the pattern and want to just call it a variable, like so:

```haskell
castConst cstr = cstr
```

But GHC will complain that the types don't match up. What's *actually* happening is that the pattern match `castConst (Const str)` is unpacking a constructor at type `Const :: String -> Const String Int`, and then we repack with a constructor at type `Const :: String -> Const String Double`. Since the actual runtime value doesn't change at all, we could use `unsafeCoerce` or even a safe `coerce`, since the type variable has a phantom role.

You should not need to implement `just` for your custom datatype. I think the easiest approach would be something like:

```haskell
data CustomMaybeInt
    = JustInt Int
    | NothingInt

instance PersistField CustomMaybeInt where
    toPersistValue cmi = toPersistValue $ case cmi of
        JustInt i -> i
        NothingInt -> customValue

    fromPersistValue pv = do
        i <- fromPersistValue pv
        pure $ 
            if i == customValue
            then NothingInt
            else JustInt i 
```

This should work transparently with `persistent` and `esqueleto`'s query functionality.

You can make it generic in the value that is contained, but you'll want to implement something like:

```haskell
instance (HasDefaultNullValue a) => PersistField (CustomMaybe a) ...

class PersistField a => HasDefaultNullValue a where
    nullValue :: Proxy a -> a
```

This will require that you have unique instances per types. This could be fine but might be confusing.

**Comment by googleson78** [comment]
Haha, I'm actually aware of this from other haskell/agda stuff, I guess my brain just wasn't in "types matter" mode :sweat_smile: Thanks for the great explanation! :heart:

I was thinking I'm going to need something similar to `just` when doing outer joins, because I'm currently using `just` for my `on` clauses situations like this:
```haskell
from \(x `LeftOuterJoin` y) -> do
  on $ just (x ^. SomeXField) ==. y ?. YId
```
where `YId` is not a `CustomMaybeInt` but just `Int64` (the primary key of `y`).

Now that I'm writing this out I'm realising my issue is probably that I'm trying to use a type different from `YId` to refer to `YId`

**Comment by parsonsmatt** [comment]
Yeah, you'll need some kind of cast function. If they share the same underlying representation in SQL then you can use `veryUnsafeCoerceSqlExprValue` at a specific type. Eg:

```haskell
intToCustomMaybe :: SqlExpr (Value Int) -> SqlExpr (Value CustomMaybeInt)
intToCustomMaybe = veryUnsafeCoerceSqlExprValue
```

**Comment by googleson78** [comment]
Closing this since my original problem was solved (and it's not really that related to `esqueleto` anyway). Thanks!
