### ISSUE TITLE
[Question] How to load References using Foreign Keys and serialize into JSON.

### ISSUE THREAD

**Issue by AliNisarAhmed** [bitemyapp/esqueleto#192]
I am a Haskell beginner trying to make my first web app with Servant and Elm.

Not sure if this is the right place to ask such questions, but I will ask anyway.

So the model looks like this: (I am using PostgreSQL)

```haskell
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
User
    firstName Text
    lastName Text
    userName Text
    UniqueUserName userName
    pwd ByteString
    deriving Eq Show

Question json
    title Text
    content Text
    created UTCTime default=now()
    userId UserId
    deriving Eq Show

Answer json
    questionId QuestionId
    content Text
    userId UserId
    created UTCTime default=now()
    deriving Eq Show
|]
```

What I want to fetch eventually and send to the client as JSON is a list of `Question` (each with a `User` object embedded inside), each `Question` has a list of `Answer` (with each answer having a `User` object embedded inside of it).

But to keep things simple for now, lets say I want to fetch from the DB a list of `Question` each with an `answers` field which will be a list of `Answer`.

This is my function so far

```haskell
getQuestionWithAnswers = do
  results <- select $ from $ \(ques `LeftOuterJoin` ans) -> do
    on (just (ques ^. QuestionId) ==. (ans ?. AnswerQuestionId))
    return (ques, ans)
```

This gives me `[ (Question, Maybe Answer) ]`, so if I morph this into a temporary datatype `Temp { questions: [Question], answers: [Answer] }`, for two questions, one with 2 answers and the other with none, I get the following json.

```json
{
    "answers": [
        {
            "created": "2020-07-01T21:54:13.071994Z",
            "content": "Sure, You may ask any question",
            "userId": 2,
            "id": 4,
            "questionId": 1
        },
        {
            "created": "2020-07-02T04:24:24.776641Z",
            "content": "Just ask man",
            "userId": 2,
            "id": 7,
            "questionId": 1
        },
        null
    ],
    "questions": [
        {
            "created": "2020-06-28T08:41:27.66974Z",
            "content": "Hey, I want to ask a question",
            "userId": 1,
            "id": 1,
            "title": "This is a question"
        },
        {
            "created": "2020-06-28T08:41:27.66974Z",
            "content": "Hey, I want to ask a question",
            "userId": 1,
            "id": 1,
            "title": "This is a question"
        },
        {
            "created": "2020-07-01T18:50:40.250075Z",
            "content": "Can a question now be only asked if I am logged in?",
            "userId": 2,
            "id": 2,
            "title": "A second Question"
        }
    ]
}
```

What I actually want the JSON to look like would be the following

```json
{
    "questions": [
            {
                "created": "2020-06-28T08:41:27.66974Z",
                "content": "Hey, I want to ask a question",
                "userId": 1,
                "id": 1,
                "title": "This is a question",
                "answers": [
                    {
                       "created": "2020-07-01T21:54:13.071994Z",
                       "content": "Sure, You may ask any question",
                       "userId": 2,
                       "id": 4,
                       "questionId": 1
                    },
                    {
                        "created": "2020-07-02T04:24:24.776641Z",
                        "content": "Just ask man",
                        "userId": 2,
                        "id": 7,
                        "questionId": 1
                    },
                ]
            },
            {
                "created": "2020-07-01T18:50:40.250075Z",
                "content": "Can a question now be only asked if I am logged in?",
                "userId": 2,
                "id": 2,
                "title": "A second Question",
                "answers": []             
            }
            
}
```

What I am doing right now is making two DB trips, fetching one question, then fetching all its answers, then attaching answers to a custom type QuestionWithAnswers manually. (I am doing it for one Question only, for now).

Is there a way to not do the transformation manually?

Is there a way to load References, so for example, if I wanted a `User` object embedded inside both the `Question` and `Answer` how can I achieve that?

I can try joining the three tables to get `[(Question, Answer, User)]`, but then how do I serialize it to JSON?

**Comment by belevy** [comment]
perhaps this article will help. Its a bit long but it covers a bunch.

https://www.foxhound.systems/blog/grouping-query-results-haskell/

**Comment by parsonsmatt** [comment]
It's tricky because there's a bunch of ways you might "nest" these rows, just based on the result list type. But - when you actually do the join - you know what you want to get out of it.

For the easy case, like ``User `InnerJoin` Question``, where you want something like `[{ "user": { "questions": [{}, {}, ...]}, ...]` it seems obvious. But then you have your example, where we want to do the join twice (using Experimental syntax):

```haskell
from $ 
    Table @Question
    `InnerJoin` @User
        `on` do
            \(q :& u) ->
                q ^. QuestionUserId ==. u ^. UserId
    `LeftOuterJoin` 
    Table @Answer
        `on` do
            \(q :& _ :& a) ->
                just (q ^. QuestionId) ==. a ?. AnswerQuestionId
    `LeftOuterJoin` 
    Table @User
        `on` do
            \(_ :& a :& u) ->
                a ?. AnswerUserId ==. u ?. UserId
```

That gives us a `[(Entity Question, Entity User, Maybe (Entity Answer), Maybe (Entity User))]`.

The relationship from Question to User is 1:1. A `Question` must have one associated `User`. So we don't need a `[Entity User]` to attach, just a `Entity User` directly. We know this because of the `user_id NOT NULL` field on `Question`.

Same deal with the relationship between `Entity Answer` and `Entity User` - but we get an additional guarantee, that if we have an `Answer`, we also have a `User` for that slot.

There will be duplicate `Entity Question` and `Entity User` entries - one for each `Answer` and one for `Nothing`. We know about the `Nothing` because it's a `LeftOuterJoin`, and we know about the "many" possibility since `AnswerQuestionId` is not a unique column. That means it should be joined into a list (or map from ID to list of entities).

I *think* we could reconstitute a join structure that's "smart" like this, but we'd need to keep track of the actual relationships between the tables. That information is currently lost in the `==.` function.

So what if we had something like:

```haskell
data SmartJoin from to colTyp
    = SmartJoin JoinKind (EntityField from colTyp) (EntityField to colTyp)
```

With this, we can better understand the shape of the data that what we're pulling out, based on information we can garner from the `EntityField` values. Then we can "render" this into a SQL query, and reconstitute the results based on that information.

But we need to handle multiple tables, so we need some way of composing these.

```haskell
data ComposeSmartJoin from to where
    StartSmartJoin :: SmartJoin from to typ -> ComposeSmartJoin from to
    ComposeSmartJoin ::ComposeSmartJoin a b -> ComposeSmartJoin b c -> ComposeSmartJoin a c
```

But! Hey, this doesn't fit our requirements - our initial thing had a join relationship that isn't entirely sequential:

```
-- WRONG
Question ---> User -?+> Answer -?-> User

-- RIGHT
Question -?+> Answer
   |            |
   V            V
  User         User
```

So we don't need sequencing - we need branching.

```haskell
data ComposeSmartJoin from to where
    StartSmartJoin 
        :: SmartJoin from to typ 
        -> ComposeSmartJoin from to
    BranchRight
        ::ComposeSmartJoin a b 
        -> ComposeSmartJoin b c 
        -> ComposeSmartJoin a (b, c)
    BranchLeft
        ::ComposeSmartJoin a b 
        -> ComposeSmartJoin a c 
        -> ComposeSmartJoin (a, c) b

-- which works!
join :: ComposeSmartJoin (Question, User) (Answer, User)
join =
    BranchRight
        (BranchLeft
            (StartSmartJoin questionToAnswer)
            (StartSmartJoin questionToUser)
        )
        (StartSmartJoin answerToUser)
```

This almost works! But we don't have a means of using `EntityField` on a tuple. Like, there's no `EntityField (Question, User)` data family instance - maybe there could be, if `EntityField` weren't conflated with all of the rest of `persistent`'s operations (or if we wanted to introduce unsafe instances just to get the instances). `BranchRight` and `BranchLeft` need something like a `SmartJoin` that knows how to unpack the tuple and link the two tables.

**Comment by AliNisarAhmed** [comment]
@belevy Thank you for writing the article, this is exactly what I was looking for. 

@parsonsmatt Thanks for your detailed response (will take me some time to digest that).

**Comment by parsonsmatt** [comment]
I wish it could be more helpful - unfortunately, it's an Idea that's not quite fully baked. 

Lately my development strategy with esqueleto has been to publicly wish for something and maybe give a brief idea on how it might be accomplished, and then @belevy runs with it and we get a new feature :joy: But maybe I'll actually deliver this one.
