### ISSUE TITLE
Is there a way to reuse a query executed via selectSource?

### ISSUE THREAD

**Issue by dashea** [bitemyapp/esqueleto#29]
I'm having an issue using `selectSource` (sqlite backend). Since unlike `select` the SQL statement is still running instead of the results being all pulled into memory, the stmtReset finalizer isn't being called. Reusing the `Source` results in a ErrorMisuse from sqlite, even if I use it in separate conduits, since the statement is only prepared once and there is no `sqlite3_reset` call between the executions.

Is there a way that the finalizer actions for selectSource could be called sooner (or explictly?), or a way to have it prepare separate statements instead of reusing the same one? Or is there something I need to be doing with the MonadResource?

Thanks for any help or advice.

Here's an example, two conduits with a selectSource source, error on the second one:
```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

import Control.Monad(void)
import Control.Monad.IO.Class(liftIO)
import Control.Monad.Trans.Resource(MonadResource)
import Data.Conduit(($$), (=$=), Source)
import qualified Data.Conduit.List as CL
import Database.Esqueleto
import Database.Persist.Sqlite(runSqlite)
import Database.Persist.TH

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Person
    name String
    deriving Show
|]

selectPerson :: MonadResource m => String -> Source (SqlPersistT m) (Key Person)
selectPerson name = do
    let source = selectSource $ from $ \person -> do
                       where_ $ person ^. PersonName ==. val name
                       return $ person ^. PersonId
    source =$= CL.map unValue

main :: IO ()
main = runSqlite ":memory:" $ do
    runMigration migrateAll

    void $ insert $ Person "John Smith"
    void $ insert $ Person "Jane Doe"

    selectPerson "John Smith" $$ CL.consume >>= liftIO . print
    selectPerson "Jane Doe"   $$ CL.consume >>= liftIO . print
```

**Comment by bitemyapp** [comment]
I'm investigating the issue here: https://github.com/bitemyapp/esqueleto-select-source-error-misuse

I found a workaround that sidesteps the problem with the `misuse` error you get from Sqlite but the problem as it stands is that `selectSource` is mis-implemented and unsafe with Sqlite. With PostgreSQL and MySQL it actually loads all the data into memory.

Accordingly I recommend you _not_ use `selectSource` and either load the entire dataset into memory or find a stable way to paginate through the results (ideally not limit/offset).

I will probably remove this function from Esqueleto as it's a death trap and I'll look into the upstream situation for Persistent for Sqlite, MySQL, and PostgreSQL. I think it can be fixed for PGSQL, Sqlite's situation involves the finalizer being invoked at the wrong time, MySQL could be harder to do well as the appropriate API call seems to lock all the tables your Conduit'd query touches.

**Comment by bitemyapp** [comment]
@parsonsmatt that's promising, although I'm still concerned about how `persistent-mysql` and `persistent-postgresql` work here.

**Comment by dashea** [comment]
Works with 2.5.3, thanks.
