### ISSUE TITLE
Selecting from sub query? (might not be an issue?)

### ISSUE THREAD

**Issue by Vlix** [bitemyapp/esqueleto#70]
I'm trying to use the window functions I've recently implemented in my own fork of Esqueleto, which at some point I'd want to try and make a pull request for Esqueleto proper, but I'm trying to do some custom queries with it, and I'm running into a limitation. (Or I'm dumb and don't realize this is totally doable in current Esqueleto)

I'm trying to construct this query:
```sql
select * from message
  where id in
    (select id
      from (select id,
              row_number() over (partition by chat_id order by time desc) as rn
              from message
            ) as x
      where x.rn <= 10
    );
```

I've managed to implement the following (which works, in Haskell as well as the resulting SQL query)
```sql
select id,
  row_number() over (partition by chat_id order by time desc) as rn
  from message;
```

But how would you select the id column from the resulting `SqlExpr (Value a)` and use the `x.rn <= 10` in the sub query around it?
`sub_select` will not allow the following `return`
```haskell
...
return (msg ^. MessageId, rn msg)
  where rn msg = row_number `over` (Just $ msg ^. MessageChatId)
                                 $ [desc $ msg ^. MessageTime]
```

Better yet, how do you select from a sub query?

**Comment by bitemyapp** [comment]
Can you do it as a `sub_select`? I'd need to dig in with working code to say or do much further.

**Comment by Vlix** [comment]
So this is what I've tried, but I get the resulting error shown below, so `sub_select` can't do this, or I'm using it incorrectly?

(This is the type signature of `over`, by the way)
```haskell
over :: SqlExpr (Value (WindowType a))
     -> Maybe (SqlExpr (Value b))
     -> [SqlExpr OrderBy]
     -> SqlExpr (Value a)
```

```haskell
getFromDB :: ReaderT SqlBackend IO [Entity Message]
getFromDB = select $ from $ \msg -> do
    where_ $ msg ^. MessageId `in_` subListQ
    return msg
  where subListQ = subList_select $ from $ \msg -> do
                      -- Something here that makes `msg`
                      -- come/be from `lastSubQ`?
                      return $ msg ^. MessageId
        lastSubQ = sub_select $ from $ \msg -> return (msg ^. MessageId, rn msg)
          where rn msg = row_number `over` (Just $ msg ^. MessageChatId)
                                         $ [desc $ msg ^. MessageTime]
```
```
.../DB.hs:107:33: error:
    • Couldn't match type ‘SqlExpr (E.Value Int64)’ with ‘E.Value a’
      Expected type: query0 (SqlExpr (E.Value (Key Message)),
                             E.Value a)
        Actual type: query0 (SqlExpr (E.Value (Key Message)),
                             SqlExpr (E.Value Int64))
    • In the second argument of ‘($)’, namely
        ‘from $ \ msg -> return (msg ^. MessageId, rn msg)’
      In the expression:
        sub_select $ from $ \ msg -> return (msg ^. MessageId, rn msg)
      In an equation for ‘lastSubQ’:
          lastSubQ
            = sub_select
              $ from $ \ msg -> return (msg ^. MessageId, rn msg)
            where
                rn msg
                  = row_number `over` (Just $ msg ^. MessageChatId)
                    $ [desc $ msg ^. MessageTime]
    • Relevant bindings include
        lastSubQ :: (SqlExpr (E.Value (Key Message)), E.Value a)
          (bound at .../DB.hs:107:9)
```

**Comment by Vlix** [comment]
The description for `sub_select` also states:
```
Execute a subquery SELECT in an expression. Returns a simple value so should be used only when the SELECT query is guaranteed to return just one row.
```
But I explicitly need the `id` row instead of the `row_number` row.

**Comment by jprider63** [comment]
Did you get this working @Vlix? Could you share your `over` function?

**Comment by jprider63** [comment]
Great thanks! I'll try to get subqueries working once you make the pull request.

**Comment by jprider63** [comment]
I ended up implementing `over` [here](https://github.com/jprider63/esqueleto/commit/259119d28fe66c09fd743100a9473d2a364ff77b#diff-c695f551a7ff1d68efde111150ca873bR1832). It works for me. I haven't tried subqueries or adding it to the language yet.

**Comment by jprider63** [comment]
I've been playing with subqueries a bit. I think we need something along the lines of the following function and a `From query expr backend (expr (Value val))` instance. 

```
select_subquery :: (From query expr backend b) => query b -> (b -> query c) -> query c
```

Then we could do something along the lines of:

```
select $ select_subquery (mySubquery) $ \subqueryRow@( a, b) -> do
    where_ (b ^. MyEntityField ==. ...)
    return a
```

I'm not sure how to implement `select_subquery` yet. I noticed that it looks like `bind` and it actually compiles with the following, even though it produces the wrong behavior.

```
select_subquery = (>>=)
```

**Comment by jprider63** [comment]
@Vlix I have [basic subqueries working](https://github.com/jprider63/esqueleto/blob/18b933532aee3cac98583a77501b1458acbbaceb/src/Database/Esqueleto/Internal/Sql.hs#L2001). Subqueries can currently return entities and values by using the `as` function. It's still rough, and I haven't tried other expressions like composite keys, lists, etc. Ideally this can be extended so that you can have joins with subqueries.

**Comment by belevy** [comment]
@parsonsmatt I have been looking at this. I know you just did a bunch of work on sub selects but your changes didn't fundamentally change the semantic meaning of them but maybe you have opionions re this. I have been looking at this problem in the context of UNION since even if we get union without the ability to sub select it will be impossible to order the results of a union. I was thinking maybe the syntax should be something like.

```haskell
select $ fromQuery $ do
   subQueryResults <- someSubQuery
   return subQueryResults
```

and in a union context

```haskell
select $ fromQuery $ do
   subQueryResult <- someSubQuery `union` otherSubQuery
   orderBy (fst subQueryResult)
   return subQueryResult
```

this would make `fromQuery` be a `SqlQuery (SqlQuery a) -> SqlQuery a` if i am not mistaken. 

The main issue with this syntax is that its unclear what one does with multiple sql queries. I am not sure how to make that a type error. This then leads to an api like

```haskell
select $ fromQuery someSubQuery $ \(subQueryResults) ->
   return subQueryResults
```

so `fromQuery` would be `SqlQuery a -> (a -> SqlQuery b) -> SqlQuery b` I am not sure how big of a fan I am of this. Though this appears to be what jprider ended up with.

Either way I am continuing to look. Hopefully I have a good idea. Let me know if you have any thoughts.

**Comment by Vlix** [comment]
Ah, it was you! @belevy :smile: 
@parsonsmatt #172 just made this possible, IIRC.

**Comment by belevy** [comment]
@jprider63 definitely did a bunch of leg work for the subquery bits but yah, this one took a while. :)

**Comment by Vlix** [comment]
A thank you for @jprider63 as well 😄
